### ISSUE TITLE
5. Making the Tank Move

### ISSUE THREAD

**Issue by suchaHassle** [MakeSchool-Tutorials/Tank-Unity-VR#1]
TankController class references an unassigned Tank Object. Include something along the lines of 
```cs
tank = GameObject.Find("Tank").GetComponent<Tank>();
```
in the Start method.

**Comment by zbarryte** [comment]
It's best to discourage use of `GameObject.Find` as it's both a costly operation and a rather unsafe one.  It relies on a GameObject having a specific name, and involves searching the entire scene for an object.  If `tank` is a pubic or serialized field, it would be best to resolve that in the editor, by dragging the proper object into that field's input box.

**Comment by suchaHassle** [comment]
I hadn't realized that `Tank` was a public variable. I could've provided a reference in the Unity project.
